# Generated by Django 2.1.1 on 2018-09-21 15:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enterprises',
            old_name='time',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='time',
            new_name='end_time',
        ),
        migrations.AddField(
            model_name='enterprises',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='students',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
