# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-02 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_users_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessions',
            name='uid',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
