# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-02 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_sessions_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprises',
            name='picname',
            field=models.CharField(default='aaa', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enterprises',
            name='session_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enterprises',
            name='uid',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
