# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-02 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_auto_20181002_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessions',
            name='qr_imgname',
            field=models.CharField(default='qr', max_length=255),
            preserve_default=False,
        ),
    ]
