# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-03 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_auto_20181003_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprises',
            name='contacts',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='enterprises',
            name='phone',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='sessions',
            name='summary',
            field=models.TextField(default='总结待填写...'),
        ),
    ]
