# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-08 06:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_students_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessions',
            name='artivle',
            field=models.CharField(default='aaa', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sessions',
            name='person_number',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
