# Generated by Django 2.1.1 on 2018-09-19 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_enterprise_student'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Enterprise',
            new_name='Enterprises',
        ),
        migrations.RenameModel(
            old_name='Student',
            new_name='Students',
        ),
    ]
