# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-01 05:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20180922_1344'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sessions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enterprise', models.CharField(max_length=100)),
                ('start_time', models.DateTimeField()),
                ('place', models.CharField(max_length=100)),
                ('volunteer', models.CharField(max_length=32)),
                ('summary', models.TextField()),
            ],
            options={
                'db_table': 'session',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
                ('phone', models.CharField(max_length=16)),
                ('email', models.CharField(max_length=50)),
                ('addtime', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.RemoveField(
            model_name='enterprises',
            name='enterprise',
        ),
        migrations.RemoveField(
            model_name='enterprises',
            name='place',
        ),
        migrations.RemoveField(
            model_name='enterprises',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='students',
            name='enterprise',
        ),
        migrations.RemoveField(
            model_name='students',
            name='place',
        ),
        migrations.RemoveField(
            model_name='students',
            name='start_time',
        ),
        migrations.AddField(
            model_name='enterprises',
            name='contacts',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enterprises',
            name='phone',
            field=models.CharField(default=110, max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='students',
            name='phone',
            field=models.CharField(default=111, max_length=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='students',
            name='major',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='students',
            name='school',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='students',
            name='stu_name',
            field=models.CharField(max_length=32),
        ),
    ]
